### ISSUE TITLE
Is a business website allowed to use this plugin?

### ISSUE THREAD

**Issue by architchandra** [digitalbutter/craft-simplesheet#12]
Considering that you're using a non-commercial instance of Handsontable for this plugin—which clearly disallows any commercial use, will it legal for a business website to be using this plugin (the website will be used to market the business's commercial offerings)?

**Comment by dgjackson** [comment]
Hey there, thanks for your interest.

With regards to commercial use, the Handsontable licence is fairly clear on this. You'll want to acquire a commercial licence to use this for commercial reasons.

If in doubt, definitely check with the Handsontable team for confirmation on your specific use-case!
