### ISSUE TITLE
Rearranging Table Columns / Row doesnt work

### ISSUE THREAD

**Issue by nickwanhere** [digitalbutter/craft-simplesheet#2]
I have follow data in the sheet

<img width="647" alt="Hello_-_Test" src="https://user-images.githubusercontent.com/522296/87496898-0b424b00-c687-11ea-8ec7-cede71d4b3e0.png">

If I move Column F before C, and save. It wont save.

**Comment by dgjackson** [comment]
Resolved in v1.0.2
