### ISSUE TITLE
Changes doesnt got save when doing Ctrl Save unless you click outside the sheet before save

### ISSUE THREAD

**Issue by nickwanhere** [digitalbutter/craft-simplesheet#3]
I have existing data, manually click save / save and continue which are fine.

Here is the testing
- Insert Column Left , Type in the cell under the new column, Ctrl Save

I think Ctrl Save doesnt catch the latest table changes

**Comment by dgjackson** [comment]
Can confirm this is the case. When a cell is 'entered' for editing, changes are not committed until either the Enter/Return key is pressed or the active cell is changed.

This behavior will be updated in v1.0.2 to automatically commit a cell when the save shortcut is pressed.

**Comment by dgjackson** [comment]
Resolved in v1.0.2
