### ISSUE TITLE
Remove rows/columns not saving

### ISSUE THREAD

**Issue by nickwanhere** [digitalbutter/craft-simplesheet#5]
Step to reproduce

Situation 1: 
- Right click to remove row
- Works visually
- Save and continue
- Showing old data

Situation 2: 
- Right click to remove row 1
- Right click to remove row 2
- Works visually
- Save and continue
- Row 1 removed, not row 2

Situation 3: 
- Right click to remove row 1
- Right click to remove row 2
- Right click to remove row 3
- Right click to remove row 4
- Works visually
- Save and continue
- Row 1,2,3 removed, not row 4

I think the last changes showhow doenst got rendered

**Comment by dgjackson** [comment]
Resolved in v1.0.2
